// Editorial image registry. All photos are Unsplash License (free use).
// These are illustrative stock photographs, never photos of the events covered.
// Full credits: reports/design/image-credits.md

export interface EditorialImage {
  src: string;
  width: number;
  height: number;
  alt: string;
  caption: string;
  photographer: string;
  sourceUrl: string;
  credit?: string;
}

export const images = {
  labBeakers: {
    src: "/images/lab-beakers.jpg",
    width: 1600,
    height: 1067,
    alt: "Clear glass beakers and a flask on a white laboratory bench",
    caption: "Illustrative photo of laboratory glassware.",
    photographer: "Hans Reniers",
    sourceUrl: "https://unsplash.com/photos/lQGJCMY5qcM",
  },
  labFlasks: {
    src: "/images/lab-flasks.jpg",
    width: 1600,
    height: 960,
    alt: "Glass flasks and beakers holding pale green liquid against a mint background",
    caption: "Illustrative photo of laboratory flasks.",
    photographer: "Allison Saeng",
    sourceUrl: "https://unsplash.com/photos/Y_mNCKscZC4",
  },
  courthouse: {
    src: "/images/courthouse-columns.jpg",
    width: 1400,
    height: 875,
    alt: "Stone courthouse facade with tall columns behind trees",
    caption: "Illustrative photo of a courthouse; not the court in this case.",
    photographer: "Danny Greenberg",
    sourceUrl: "https://unsplash.com/photos/DWELZ1vtM6Y",
  },
  federalBuilding: {
    src: "/images/federal-building.jpg",
    width: 1400,
    height: 875,
    alt: "Columned government-style building on a city corner with a US flag",
    caption: "Illustrative photo of a government building; not a location named in this report.",
    photographer: "Joshua Woroniecki",
    sourceUrl: "https://unsplash.com/photos/Skfy8ljB7X4",
  },
  documents: {
    src: "/images/documents-stack.jpg",
    width: 1600,
    height: 1064,
    alt: "Close-up of a thick stack of paper records",
    caption: "Illustrative photo of paper records.",
    photographer: "Camilo Rueda López",
    sourceUrl: "https://unsplash.com/photos/3CLPBgNuX40",
  },
  warehouse: {
    src: "/images/warehouse-aisle.jpg",
    width: 1200,
    height: 750,
    alt: "Warehouse aisle lined with shelving and cardboard boxes",
    caption: "Illustrative photo of a warehouse; not a facility named in this report.",
    photographer: "Russ Murray",
    sourceUrl: "https://unsplash.com/photos/M7G_m5XJ-go",
  },
  shippingBox: {
    src: "/images/shipping-box.jpg",
    width: 1600,
    height: 1067,
    alt: "An open, empty cardboard shipping box on a white surface",
    caption: "Illustrative photo of a shipping box.",
    photographer: "Kelli McClintock",
    sourceUrl: "https://unsplash.com/photos/d21p_xkPoMA",
  },
  gavel: {
    src: "/images/gavel-book.jpg",
    width: 1600,
    height: 820,
    alt: "A wooden gavel resting on a closed book",
    caption: "Illustrative photo of a gavel; not the court in this case.",
    photographer: "Sasun Bughdaryan",
    sourceUrl: "https://unsplash.com/photos/NB1dUts3ROU",
  },
  capitol: {
    src: "/images/capitol-dome.jpg",
    width: 1600,
    height: 1067,
    alt: "The dome of the United States Capitol against a cloudy sky",
    caption: "Illustrative photo of the U.S. Capitol.",
    photographer: "Simon Ray",
    sourceUrl: "https://unsplash.com/photos/0MCrSONaYu8",
  },
  pipette: {
    src: "/images/pipette-tubes.jpg",
    width: 1400,
    height: 875,
    alt: "A pipette dispensing liquid into a rack of laboratory test tubes",
    caption: "Illustrative photo of laboratory work.",
    photographer: "Nathan Rimoux",
    sourceUrl: "https://unsplash.com/photos/iiFfGsMppBA",
  },
  envelopes: {
    src: "/images/opened-envelopes.jpg",
    width: 1400,
    height: 933,
    alt: "A pile of opened paper envelopes",
    caption: "Illustrative photo of opened mail.",
    photographer: "Sue Hughes",
    sourceUrl: "https://unsplash.com/photos/toQNPpuDuwI",
  },
  magnifier: {
    src: "/images/magnifier-paper.jpg",
    width: 1600,
    height: 1067,
    alt: "A magnifying glass resting on a printed document",
    caption: "Illustrative photo of document review.",
    photographer: "Vlad Deep",
    sourceUrl: "https://unsplash.com/photos/mCqi3MljC4E",
  },
  padlock: {
    src: "/images/padlock-door.jpg",
    width: 1400,
    height: 875,
    alt: "A padlock and chain securing a weathered metal door",
    caption: "Illustrative photo of a locked door; not a location named in this report.",
    photographer: "Sara Ghasemi",
    sourceUrl: "https://unsplash.com/photos/FztBgp6LBcY",
  },
  microscope: {
    src: "/images/microscope.jpg",
    width: 1400,
    height: 933,
    alt: "A researcher working at a laboratory microscope",
    caption: "Illustrative photo of a research laboratory.",
    photographer: "National Cancer Institute",
    sourceUrl: "https://unsplash.com/photos/rHfsPolwIgk",
  },
  testTubes: {
    src: "/images/test-tubes.jpg",
    width: 1600,
    height: 1067,
    alt: "A rack of laboratory test tubes",
    caption: "Illustrative photo of laboratory test tubes.",
    photographer: "National Cancer Institute",
    sourceUrl: "https://unsplash.com/photos/RuTQYiOOz0Y",
  },
  fbiErt: {
    src: "/images/fbi-evidence-team.jpg",
    width: 1600,
    height: 1064,
    alt: "FBI Evidence Response Team members in protective suits collecting evidence outdoors",
    caption: "FBI Evidence Response Team at work. File photo; not the Apex search.",
    photographer: "FBI",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:FBI_Evidence_Response_Team_2.jpg",
    credit: "Photo: FBI / Wikimedia Commons (Public domain)",
  },
  northSiouxCity: {
    src: "/images/north-sioux-city.jpg",
    width: 1600,
    height: 1066,
    alt: "City hall in North Sioux City, South Dakota",
    caption: "North Sioux City, South Dakota, where local reports placed the searches. City hall is not a searched location.",
    photographer: "TheCatalyst31",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:City_hall,_North_Sioux_City,_SD.jpg",
    credit: "Photo: TheCatalyst31 / Wikimedia Commons (CC0)",
  },
  dojBuilding: {
    src: "/images/doj-building.jpg",
    width: 1600,
    height: 736,
    alt: "Robert F. Kennedy Department of Justice Building in Washington, D.C.",
    caption: "U.S. Department of Justice headquarters in Washington, D.C.",
    photographer: "APK",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Robert_F._Kennedy_Department_of_Justice_Building.jpg",
    credit: "Photo: APK / Wikimedia Commons (CC BY 4.0)",
  },
  hplc: {
    src: "/images/hplc-system.jpg",
    width: 1600,
    height: 1200,
    alt: "An HPLC system on a laboratory bench",
    caption: "A high-performance liquid chromatography (HPLC) system, the instrument behind most COA purity figures.",
    photographer: "Dqwyy",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:High-performance_liquid_chromatography.jpg",
    credit: "Photo: Dqwyy / Wikimedia Commons (CC0)",
  },
  lillyHq: {
    src: "/images/lilly-hq.jpg",
    width: 1600,
    height: 1200,
    alt: "Eli Lilly Corporate Center in Indianapolis, Indiana",
    caption: "Eli Lilly and Company headquarters in Indianapolis.",
    photographer: "Momoneymoproblemz",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Eli_Lilly_Corporate_Center,_Indianapolis,_Indiana,_USA.jpg",
    credit: "Photo: Momoneymoproblemz / Wikimedia Commons (CC BY-SA 4.0)",
  },
  fdaSign: {
    src: "/images/fda-white-oak.jpg",
    width: 1600,
    height: 1177,
    alt: "FDA sign at the entrance to the White Oak campus",
    caption: "FDA headquarters campus in Silver Spring, Maryland.",
    photographer: "U.S. Food and Drug Administration",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:FDA_Sign_%26_Bldg_21_at_Entrance_(5204602349).jpg",
    credit: "Photo: U.S. Food and Drug Administration / Wikimedia Commons (Public domain)",
  },
  alabamaCapitol: {
    src: "/images/alabama-capitol.jpg",
    width: 1600,
    height: 1011,
    alt: "Alabama State Capitol in Montgomery",
    caption: "Alabama State Capitol, Montgomery.",
    photographer: "DXR",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Alabama_State_Capitol,_Montgomery,_South_view_20160713_1.jpg",
    credit: "Photo: DXR / Wikimedia Commons (CC BY-SA 4.0)",
  },
  lcms: {
    src: "/images/lc-ms-lab.jpg",
    width: 1600,
    height: 1047,
    alt: "A liquid chromatograph with mass spectrometer in a laboratory",
    caption: "Liquid chromatography with mass spectrometry (LC-MS), used to confirm a compound's identity.",
    photographer: "Sarka Na kopci",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Liquid_chromatograph_with_mass_spectrometer_in_CAFIA_laboratory,_Czech_Republic.png",
    credit: "Photo: Sarka Na kopci / Wikimedia Commons (CC BY-SA 4.0)",
  },
  researchVials: {
    src: "/images/research-vials.jpg",
    width: 1600,
    height: 1066,
    alt: "Gloved hand working with research sample vials and well plates",
    caption: "Research samples in a laboratory. File photo.",
    photographer: "National Center for Advancing Translational Sciences",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Vials_(32419676518).jpg",
    credit: "Photo: National Center for Advancing Translational Sciences / Wikimedia Commons (Public domain)",
  },
  apexRaid: {
    src: "/images/apex-raid-illustration.jpg",
    width: 1600,
    height: 893,
    alt: "Illustration of FBI agents carrying evidence boxes out of a warehouse loading door",
    caption: "AI-generated illustration of a federal search. Not a photo of the Apex Peptides search.",
    photographer: "The Peptide Digest",
    sourceUrl: "https://peptidedigest.co",
    credit: "Photo: Illustration / The Peptide Digest",
  },
  apexWarehouse: {
    src: "/images/apex-warehouse-illustration.jpg",
    width: 1600,
    height: 893,
    alt: "Illustration of FBI agents outside a taped-off metal warehouse",
    caption: "AI-generated illustration. Not a photo of any Apex-linked property.",
    photographer: "The Peptide Digest",
    sourceUrl: "https://peptidedigest.co",
    credit: "Photo: Illustration / The Peptide Digest",
  },
} satisfies Record<string, EditorialImage>;

export type ImageKey = keyof typeof images;
